### ISSUE TITLE
[Question] Can latest kAFL works on target with no source code?

### ISSUE THREAD

**Issue by jingfelix** [IntelLabs/kAFL#121]
Hi! 

I am working on fuzzing Linux kernel using kAFL. Some third-party distributions use modified kernel and may not publish their source code, so I am wondering if the latest version of kAFL can fuzz targets without source code. 

Also I notice that a new example named "linux-user" is working in progress. Hope to see tutorial about it!

Thanks again for creating and maintaining such a great tool.

**Comment by il-steffen** [comment]
Hi,

I cannot tell you what you can fuzz or not, but kAFL has been used for Windows and OSX fuzzing so in general this should be possible.

Updated linux userspace tutorial is planned, yes.

**Comment by jingfelix** [comment]
Thanks! I will consider proceeding my work after the userspace tutorial is ready.

**Comment by Wenzel** [comment]
Thanks @il-steffen for answering this question !
@jingfelix feedback from the community is extremely valuable to us, so thank you for sharing your problem and questions with us.

I just opened the [Github Discussions tab](https://github.com/IntelLabs/kAFL/discussions) to better engage and connect with our community, get their questions regarding the project or some of its components, their specific use cases, etc ..

Feel free to use it !
