### ISSUE TITLE
Warning: Invalid sharedir...

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kAFL#132]
Another message in kAFL's output:
~~~
Warning: Invalid sharedir...
~~~

Why is it popping up, and should we do something about it ?

**Comment by il-steffen** [comment]
The message is produced by underlying NyxQemu when launching `kafl fuzz` with --sharedir pointing to an invalid directory. There is no impact as long as the sharedir is not actually used, i.e. guest pulling files from host via `vmcall/hget`. A separate file access error will be produced then.
