### ISSUE TITLE
How to apply Redqueen to kAFL

### ISSUE THREAD

**Issue by 5angjun** [IntelLabs/kAFL#146]
Hi there!!

Now i'm trying to learn and analysis kAFL 0.2v

But i stucked with Applying RedQueen techniques to kAFL 0.2v.

Because [Docs](https://github.com/IntelLabs/kAFL/blob/kafl_0.2/doc/README.Redqueen.md) is invalid.

so Can i get the tips for setting Redqueen to kAFL v0.2?

My environment is 
OS : ubuntu 20.04.5 LTS
kernel : 5.15.0-56-generic or kAFL 5.11.4
CPU : Intel 12700K

`
1. I success to run kAFL 0.2v without redqueen & grimoire.

2. Stuck in this point
git clone https://github.com/RUB-SysSec/redqueen.git ~/redqueen

cd ~/redqueen
./install.sh
`
![Screenshot from 2022-12-27 15-04-19](https://user-images.githubusercontent.com/76202024/209619365-e4fad2b4-4674-47fc-9b14-0b1234128838.png)
![Screenshot from 2022-12-27 15-04-35](https://user-images.githubusercontent.com/76202024/209619368-aa8d85fe-a940-49e4-a769-a80f5cc089f2.png)

**Comment by il-steffen** [comment]
Redqueen (and Grimoire) have always been integrated in the IntelLabs/kAFL repo. You cannot install the redqueen repo on top of it.

If you want to test Redqueen separately, follow only the installation from Redqueen repo and manually check differences to the original kAFL repo:

https://github.com/RUB-SysSec/kAFL - original release
https://github.com/RUB-SysSec/redqueen - updated components with Redqueen extension
https://github.com/RUB-SysSec/grimoire/ - updated only kAFL-Fuzzer component
