### ISSUE TITLE
does it only run on physical host machine and cannot start in virtual machines like on vmware？

### ISSUE THREAD

**Issue by liujf628995** [IntelLabs/kAFL#199]
My computer is a Win10 machine,I tried to make kafl on linux by vmware,but could not find intel_pt in /proc/cpuinfo.Then I found the intel_pt info in WSL on the same host machine,I thought that means my cpu is support for intel_pt.
Can this project only run on physical Linux machines?

**Comment by Wenzel** [comment]
Hi @liujf628995 

kAFL is based on a modified KVM, so it requires a Linux host machine, bare-metal.
Nesting kAFL inside another VM is an open ticket at this point: https://github.com/IntelLabs/kAFL/issues/142

**Comment by liujf628995** [comment]
> Hi @liujf628995
> 
> kAFL is based on a modified KVM, so it requires a Linux host machine, bare-metal. Nesting kAFL inside another VM is an open ticket at this point: #142

Thanks for your anwser! I think it will be helpful that writing the operational requirement into README.I have tried many times to locate this problem.

**Comment by Wenzel** [comment]
> I think it will be helpful that writing the operational requirement into README.I have tried many times to locate this problem.

The hardware and software requirements are specified in the documentation:
I think it will be helpful that writing the operational requirement into README.I have tried many times to locate this problem.

And there is a note specifying that VM-based setups are not supported:
![image](https://github.com/IntelLabs/kAFL/assets/964610/357f9c2f-1152-42ae-be00-e1f5c737af8a)
