### ISSUE TITLE
Mutation Bugs in havoc stage ( find_diffs )

### ISSUE THREAD

**Issue by 5angjun** [IntelLabs/kAFL#223]
https://github.com/IntelLabs/kafl.fuzzer/blob/4d9404ddd7b0760d419b4ff476b63d7e1b8c6201/kafl_fuzzer/common/util.py#L89

I found dead code that return always 
```
first_diff = 1
last_diff = min(len(data_a), len(data_b)) -1
```
so this code cannot find different segment payload A and payload B.

i think it need to patch havoc stage like this.

this bugs exist from kAFL 0.2v to kAFL 0.7v
```
def find_diffs(data_a, data_b):
    first_diff = 0
    last_diff = 0
    for i in range(min(len(data_a), len(data_b))):
        if data_a[i] != data_b[i]:
            if first_diff == 0:
                first_diff = i
            last_diff = i
```

**Comment by Wenzel** [comment]
Thanks again for the bug report !
Fixed by https://github.com/IntelLabs/kafl.fuzzer/pull/73
