### ISSUE TITLE
Lock/Release mechanism in qemu instance start/restart need improvements

### ISSUE THREAD

**Issue by P4R54** [IntelLabs/kAFL#24]
Hello 
Thanks for publishing this project
In line 530 of [kAFL-Fuzzer/common/qemu.py](https://github.com/IntelLabs/kAFL/blob/8c45d915c5f8fd858377ad23e9e1528e0b64f252/kAFL-Fuzzer/common/qemu.py#L530) sleep(0.1) is added to prevent any race between old instance of qemu and new instance.
In many test cases , understood that 0.1 seconds is not enough to prevent this condition, increased this time little by liitle and reached 3 seconds , i didn't get any errors with 3 seconds of sleep but its not a good way for preventing as you mentioned in  

> TODO: Need to wait here or else the next instance dies in set_payload()
>         # Perhaps Qemu should do proper munmap()/close() on exit?

system config: 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
stepping	: 10
microcode	: 0xde
cpu MHz		: 800.059
cache size	: 9216 KB

with 16 gb of ram . 4096 gb for qemu instance

**Comment by il-steffen** [comment]
Hi. Thanks for the comment. The timing here probably depends on your machine's ability to restart qemu. I suspect you will get a very different result if you change the RAM of your VM instance.

On the positive side, these issues will probably disappear with the upcoming 'Nyx' backend.
