### ISSUE TITLE
How can i scale up the Target VM's CPU core?

### ISSUE THREAD

**Issue by 5angjun** [IntelLabs/kAFL#241]
Hello, i'm sangjun.

I really interested in your project.

I want scale up the Target vm's Ram & cpu core.

So i fix some script in kafl/examples/windows_x86_64/Vagrantfile
https://github.com/IntelLabs/kafl.targets/blob/master/windows_x86_64/Vagrantfile
```
    # rsync doesn't work on WinRM
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :libvirt do |libvirt|
        libvirt.storage_pool_name = "newpool"
        # the qcow will be owned by the user
        # so kafl can use the VM's qcow as well
        libvirt.uri = "qemu:///session"
        # spice is better than VNC (mouse handling)
        libvirt.graphics_type = "spice"
        libvirt.cpus = 5
        libvirt.memory = 8192



```

But after vagrant up the vm, the max CPU proccessor limit is 4.

is there Any other way to scale up the number of the VM's CPU core??

However, I can scale up the ram size normally, but I can't scale up the CPU core...

Thanks.

![스크린샷, 2023-10-09 16-52-07](https://github.com/IntelLabs/kAFL/assets/76202024/f40a4e40-1103-407b-810d-bb0fc8c9b998)

**Comment by Wenzel** [comment]
Hello @5angjun,

> I really interested in your project.

Thank you for your interest and opening issues on the problems that you face, this is a good learning experience for us.

> But after vagrant up the vm, the max CPU proccessor limit is 4.

I tested this myself, first by configuring the `libvirt.cpus` value to `1`, which worked.
And then by testing `5` and `6`.

Looking at the virt-manager/CPU panel, the value is really propogated to libvirt XML domain.

So at this point I really believe this is a limitation of the Windows 10 Entreprise Evaluation image that we are using as a template.

You need to activate it ot unlock all of the features and remove hardware limitations.

**Comment by Wenzel** [comment]
Update: I found a solution ! :tada: 

So libvirt has a very dump way of adding more CPUs, by simply adding another `socket` to the hardware.
And Windows 10 might be limited to 4 sockets max.

What you can do is play instead with the CPU topology, specifying how many cores are to be found per socket:
- https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#provider-options
- https://libvirt.org/formatdomain.html#cpu-model-and-topology

![image](https://github.com/IntelLabs/kAFL/assets/964610/a17f2d36-b0f3-49dc-8d24-8497716133bd)

Testing with 1 socket and 6 cores:
![image](https://github.com/IntelLabs/kAFL/assets/964610/f2511624-2852-4e8a-8e4f-cc6032fb1dc4)

![image](https://github.com/IntelLabs/kAFL/assets/964610/85f14a3f-d393-4209-a9b6-d57f0a7e46fe)


It works !
