### ISSUE TITLE
How to use packer_windows_libvirt_amd.box in Vmware / Virtualbox?

### ISSUE THREAD

**Issue by 5angjun** [IntelLabs/kAFL#244]
Hello, I'm sangjun who is very interested in your awesome project.

There is one thing that is being set for convenience while using kAFL.

Instead of using packer_windows_libvirt_amd64.box to run a vm using libvirt on Linux, I want to run the same image on a Windows host machine through virtual box or vmware. 
( packer_windows_libvirt_amd64.box is generated from make biuld command )
https://github.com/IntelLabs/kafl.targets/tree/master/templates/windows

However, no matter how much I set up the vagrantfile, it eventually failed. Any good ideas?

I would like to reproduce the crash using the same box image in vmware or virtualbox rather than qemu. However, changing the provider of vagrant to virtualbox or vmware instead of libvirt failed.

Thanks

If there is a solution to this, I would appreciate it if you could write the command.

**Comment by Wenzel** [comment]
Hi @5angjun,

unfortunately, kAFL is only based on a modified QEMU/KVM virtualization stack, you wouldn't be able to run it on Windows, even if you could generate the Packer Vagrant box for VirtualBox or VMware.

And nested setup scenarios (Windows VMware > Linux QEMU/KVM kAFL > target ) aren't supported yet https://github.com/IntelLabs/kAFL/issues/142
