### ISSUE TITLE
Docker image on Dockerhub and built from Dockerfile has issues

### ISSUE THREAD

**Issue by dkoch144** [IntelLabs/kAFL#248]
I installed dependencies and built with `make deploy -- --tags kernel` and then rebooted.

```bash
uname -r
6.0.0-nyx+
```

I get this issue when I run a container based on the image pulled from Dockerhub (intellabs/kafl:latest) as well as when I build the image locally with the latest Dockerfile from master.

```bash
docker run -it --device /dev/kvm --user $(id -u):$(id -g) --group-add $(getent group kvm | cut -d: -f3) kafl:latest fuzz
[7] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib/parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[7] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

When I was building I did run into issues with python 3.8 vs 3.9 but I resolved those with #175

**Comment by Wenzel** [comment]
Hey @dkoch144,

thank you very much for reporting this problem ! 💯 
This seems related to Pyinstaller, judging by this very similar issue reported a few months ago:
https://github.com/pyinstaller/pyinstaller/issues/7692

I'll try to update the pyinstaller dependency.

**Comment by Wenzel** [comment]
Confirm the latest image on Dockerhub starts as expected.

use `--pull always` to force the refresh !

I'm also keen to get your feedback on how you use the kAFL docker image !

**Comment by dkoch144** [comment]
Thanks for the fix! 

I'm just looking to benchmark the Redqueen feature currently and I didn't want to have to do the cgroups myself.

I see that the linux userspace tutorial is still in the works. Can I just follow the tutorial at https://github.com/RUB-SysSec/redqueen to get going?
