### ISSUE TITLE
"kafl fuzz" command crashes with Qemu fails to load Windows10 VM

### ISSUE THREAD

**Issue by jjeongxu** [IntelLabs/kAFL#265]
Hi,

I really appreciate the project that you built.

I have a problem here..
When I try to run "kafl fuzz" after setting up the fuzzer and environment(Windows 10 VM, target driver, vuln_test.exe, etc..), it crashes few minutes after showing up this message
![Screenshot from 2024-01-04 20-12-26](https://github.com/IntelLabs/kAFL/assets/143536771/4e61f899-f05a-4651-a121-483ebbdb645d)

and the error log varies.
Mostly, it says "assertion failure in 'qemu/nyx/snapshot/block/block_cow.c:450' assert(self->offset_primary < self->cow_primary_size);"
![Screenshot from 2024-01-04 20-17-41](https://github.com/IntelLabs/kAFL/assets/143536771/abaebd2a-0544-4162-9af7-ca7d3cadef02)

but sometimes, it says "error no.32 broken pipe"

Command below is the command that I used to run the fuzzer
```
kafl fuzz -w work --seed-dir seed --redqueen -p 1 --t-soft 255 --purge -i result.json --use_call_stack --t-hard 255
```

And the text below is the command that kAFL used to run the VM with QEMU
```
/home/dltkrgksmf/kAFL/kafl/qemu/x86_64-softmmu/qemu-system-x86_64
	-enable-kvm
	-machine kAFL64-v1
	-cpu kAFL64-Hypervisor-v1,+vmx
	-no-reboot
	-net none
	-display none
	-chardev socket,server,id=nyx_socket,path=/home/dltkrgksmf/kAFL/kafl/examples/windows_x86_64/work/interface_0
	-device nyx,chardev=nyx_socket,workdir=/home/dltkrgksmf/kAFL/kafl/examples/windows_x86_64/work,worker_id=0,bitmap_size=65536,input_buffer_size=131072
	-device isa-serial,chardev=kafl_serial
	-chardev file,id=kafl_serial,mux=on,path=/home/dltkrgksmf/kAFL/kafl/examples/windows_x86_64/work/serial_00.log
	-m 8192
	-drive file=/home/dltkrgksmf/.local/share/libvirt/images/windows_x86_64_vagrant-kafl-windows.img
	-monitor unix:/tmp/monitor.sock,server,nowait
	-fast_vm_reload path=/home/dltkrgksmf/kAFL/kafl/examples/windows_x86_64/work/snapshot/,load=off
```

I ensured that drive file in '/home/dltkrgksmf/.local/share/libvirt/images/windows_x86_64_vagrant-kafl-windows.img' is totally flawless. Because it runs fine on Vagrant.
And I also checked that Windows10 VM runs 'test_vuln.exe' when it boots.

[Kernel info]
![Screenshot from 2024-01-04 20-25-36](https://github.com/IntelLabs/kAFL/assets/143536771/60315979-6656-4e3c-88b9-a3793153d77a)

[QEMU info]
![Screenshot from 2024-01-04 20-26-23](https://github.com/IntelLabs/kAFL/assets/143536771/54888731-ab48-43a3-a13c-9a5eac36eca0)

[QEMU not booting up the VM]
![Screenshot from 2024-01-04 21-30-47](https://github.com/IntelLabs/kAFL/assets/143536771/12c18e88-8034-4061-869a-05bc3b9cace5)

Thank you.

**Comment by Wenzel** [comment]
Hi @jjeongxu and thanks for the detailed bug report !

I rebuilt the Windows image from scratch and started a new campaign, but couldn't repro the fuzzer or QEMU crashes you experienced.

A couple of things though:

Your `kafl fuzz` command has the following additional parameters
- `-i  results.json`
- `--use_call_stack`

These parameters aren't in the documentation:
https://intellabs.github.io/kAFL/reference/fuzzer_configuration.html

Are you using a kAFL fork by any chance ?

Additionally, regarding the issue of "[QEMU not booting up the VM]", when you boot the VM via kAFL, libvirt isn't involved and can't update its internal state.
if you want to start the VM via libvirt, use virsh API, and tweak the QEMU command line (see [QEMU command line passthrough](https://libvirt.org/kbase/qemu-passthrough-security.html))

**Comment by jjeongxu** [comment]
Hi, @Wenzel 
I really appreciate your reply! Thank you for reaching out

I'm using a slightly modified version of kAFL, and the issue was that it couldn't load the target driver into the VM Windows 10's vuln_test process, and there was no single issue with kafl.qemu or kAFL. This resulted in the problem of getting stuck in the infinite loop of vuln_test's main() function( while(1) { CreateFile() } ).

Now, everything is resolved, and I sincerely appreciate your response.

Wishing you a Happy New Year with lots of blessings!

**Comment by DefenceLabs** [comment]
Hello, just wanted to know how exactly you fixed this error? Thanks

**Comment by jjeongxu** [comment]
> Hello, just wanted to know how exactly you fixed this error? Thanks

Sorry for checking it too late. This was my stupid personal mistake. I couldn't get a HANDLE using CreateFile(), and in my harness, it caused an error because it kept allocating resources in an infinite loop while sending DeviceIoControl() calls. Once I fixed it to properly obtain a HANDLE with CreateFile(), the issue was resolved.
