### ISSUE TITLE
Intel 13th gen: Intel PT is not supported on this CPU

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kAFL#276]
Potential compatibility issue with 13th gen spotted by @GanbaruTobi in https://github.com/IntelLabs/kAFL/issues/275.

Current workaround is to append `mitigations=off` in GRUB's kernel command line.

**Comment by nj00001** [comment]
I've tested it on an i7 13700 with nyx-6.8 kernel installed and everything works fine, no need to make changes to grub!

**Comment by Wenzel** [comment]
Awesome, thanks for the confirmation !

**Comment by Wenzel** [comment]
solved by https://github.com/IntelLabs/kAFL/pull/284
