### ISSUE TITLE
In the kafl windows target, using the Sleep() function after a snapshot recovery seems to cause the client to stop running

### ISSUE THREAD

**Issue by nj00001** [IntelLabs/kAFL#281]
Modifying the windows sample program selffuzz_test directly should reproduce the problem

```
    kAFL_hypercall(HYPERCALL_KAFL_NEXT_PAYLOAD, 0);
    kAFL_hypercall(HYPERCALL_KAFL_ACQUIRE, 0);
    
    fuzzme(payload_buffer->data, payload_buffer->size);
    Sleep(1);
    kAFL_hypercall(HYPERCALL_KAFL_RELEASE, 0);
```
![image](https://github.com/IntelLabs/kAFL/assets/42004790/367ed6ae-c7ff-4edf-98a0-936d7fdbea00)

The result is that every fuzz results in a timeout.
And in my tests, many functions with hibernation cause this problem, such as Sleep(), select(), MsgWaitForMultipleObjectsEx(). This is actually quite a serious problem, since many programs use sleep or blocking to synchronize in one way or another.

**Comment by bjloed** [comment]
Oh, I met the same bug too. HAHA

**Comment by wxzzzzzzz** [comment]
@nj00001 Have you solved this problem?

**Comment by wxzzzzzzz** [comment]
@nj00001 Have you resolved this issue?

**Comment by nj00001** [comment]
> [@nj00001](https://github.com/nj00001) Have you resolved this issue?

https://github.com/nj00001/QEMU-Nyx-8

**Comment by wxzzzzzzz** [comment]
> > [@nj00001](https://github.com/nj00001) Have you resolved this issue?
> 
> https://github.com/nj00001/QEMU-Nyx-8

Thank you for your reply.

I ran your code.
However,there's an infinite loop here.
[        while (wait_main_thread){](https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/fast_vm_reload_sync.c#L182)
The set_wait function was not called.

After I removed the code:
`while (wait_main_thread){
            sleep(1);
        }`
It will block here
https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/synchronization.c#L263
The lock needs to be released below.
https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/interface.c#L141
I believe the problem is that QEMU cannot receive data from the fuzzer.
Have you encountered this issue before?

**Comment by nj00001** [comment]
> > > [@nj00001](https://github.com/nj00001) Have you resolved this issue?
> > 
> > 
> > https://github.com/nj00001/QEMU-Nyx-8
> 
> Thank you for your reply.
> 
> I ran your code. However,there's an infinite loop here. [ while (wait_main_thread){](https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/fast_vm_reload_sync.c#L182) The set_wait function was not called.
> 
> After I removed the code: `while (wait_main_thread){ sleep(1); }` It will block here https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/synchronization.c#L263 The lock needs to be released below. https://github.com/nj00001/QEMU-Nyx-8/blob/f715245bbd59d8ae7b078d2dfc5bb50fd1441244/nyx/interface.c#L141 I believe the problem is that QEMU cannot receive data from the fuzzer. Have you encountered this issue before?

The loop was set up to fix the QEMU global lock issue. This code is a bit old, and I don't remember some of the details. The inability to receive input is because it has to sleep and wait for the main thread to resume.

**Comment by nj00001** [comment]
> [@nj00001](https://github.com/nj00001) Have you resolved this issue?这个问题解决了吗？

When I was organizing old projects, I deleted all commit records. The code in my repository was later re-ported, so some code might be missing. After fixing the issue and restoring the status, I actually fuzzed many UI programs, including the Office suite. Aside from the slower speed, there were no other problems.

**Comment by wxzzzzzzz** [comment]
@nj00001 Ok, thank you!
