### ISSUE TITLE
Testing the testing branch

### ISSUE THREAD

**Issue by il-steffen** [IntelLabs/kAFL#33]
Multiple proposed fixes and updates in the testing branch, including long-standing issues like Qemu hanging on snapshot. 
Also a new Linux tutorial based on #27 and #31. 

I have kind of moved on to using the Qemu-PT/KVM-PT from Nyx, but let me know how it works and we can merge any fixes.

**Comment by vient** [comment]
Works fine for me. 

I have some changes on top of your testing branch which I plan to push soon, with all these changes kAFL works really stable on my setup

**Comment by vient** [comment]
It seems that fixes in testing branch are generally helpful and do not cause additional problems. On the other hand, other people may not notice it and stumble to problems which are already solved in testing. I propose to merge it to master in current state before merging any existing pull request.

**Comment by il-steffen** [comment]
Agreed, done.
