### ISSUE TITLE
Cannot find the Log file containting the syscalls the Fuzzer executes .

### ISSUE THREAD

**Issue by Altruy** [IntelLabs/kAFL#40]
I am trying to access the log file containing the syscalls. I tried the fuzzer command with the -v flag hoping that the debug log will contain the syscalls. the command:
![WhatsApp Image 2021-06-17 at 4 35 10 PM](https://user-images.githubusercontent.com/70485527/122390597-9f015300-cf8b-11eb-88a1-eeb61adca2b3.jpeg)
 however the log says "Input validation failed! Target is funky?.."
the debug.log file:
![WhatsApp Image 2021-06-17 at 4 34 38 PM](https://user-images.githubusercontent.com/70485527/122390809-ce17c480-cf8b-11eb-90be-7784888abbe7.jpeg)

If this -v flag is the way to get the syscalls how do i fix the input validation error. If not can someone guide me on how to get a log file of all the syscalls the fuzzer tries to execute?

**Comment by il-steffen** [comment]
Can you clarify what you are looking for? kAFL is not a syscall fuzzer and does not perform any syscalls directly.
The modified Qemu process talks to the host kernel + KVM. Inside the guest, your kafl_vuln_test binary is accessing the vulnerable kernel module via /proc. You could capture syscalls in either case using standard tools. You could also extend kafl_vuln_test.c to record executed syscalls and report them to the host via hprintf.

To exercise syscalls with fuzzing input, you need to write an agent that calls the syscalls you are interested in.
