### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by irenge** [IntelLabs/kAFL#49]
How does the intel PT in kAFL notifies the AFL if  a new coverage has been hit ?

**Comment by il-steffen** [comment]
kAFL-Fuzzer/common/qemu.py has all the Qemu process interaction. The patched "Qemu-PT" reads the PT buffer from hardware and parses it to a bitmap. The bitmap is returned from send_payload() in qemu.py and checked by the caller in fuzzer/process/slave.py.
