### ISSUE TITLE
`install.sh deps` may trigger machine suspend

### ISSUE THREAD

**Issue by il-steffen** [IntelLabs/kAFL#60]
On vanilla Ubuntu install, `install.sh deps` may pull in desktop packages as a dependency on qemu, which in turn may activate suspend mode and disable a remote machine. Maybe disabling recommended packages helps. Need testing..

**Comment by Wenzel** [comment]
Should we close this in light of https://github.com/IntelLabs/kAFL/pull/64 merged ?

**Comment by il-steffen** [comment]
If the Ansible setup is not pulling the "recommended" dependencies, yes.
