### ISSUE TITLE
kvm.h patch file problem

### ISSUE THREAD

**Issue by B1aNB1aN** [IntelLabs/kAFL#8]
There is a problem about kvm vmx pt io control code defined in kvm.h patch file.
The io code KVM_VMX_PT_ENABLE_ADDR3 is conflict with io code KVM_KVMCLOCK_CTRL in kvm.h.
You can see the [issus](https://github.com/RUB-SysSec/redqueen/issues/6) i opened in project redqueen for more information.

**Comment by il-steffen** [comment]
Thanks. It seems like the control codes are used on different file descriptors with their own respective handlers, so in my mind this lapse in counting should have no effect for now. Did you observe any impact?

**Comment by B1aNB1aN** [comment]
No. Changing it or not depends on you. What i mean is that i want you guys notice it in case it will make kAFL unstable.
