### ISSUE TITLE
Read timeout error with make deploy

### ISSUE THREAD

**Issue by KainaatSingh** [IntelLabs/kAFL#92]
The following error is observed when installing requirements.txt during deploy. Pip has a default timeout of 15 seconds that leads to this error when the internet connection is slow. I can recommend increasing the default timeout that helps overcome this issue.

<img width="878" alt="Pip_Default_Timeout" src="https://user-images.githubusercontent.com/44963522/183928197-b6b02ba3-7af7-47fc-9b69-79cec850ec4c.PNG">

**Comment by Wenzel** [comment]
Thanks for reporting the issue.

I would avoid tweaking pip's behavior unless it's absolutely necessary.
kAFL's installer can't take responsability for the end-user connection hazards, and modifying pip's default values as a consequence.

If you are using a VPN, maybe you should double check the connection speed and reliability.
You are likely to experiment connection hiccups with other package managers, not just pip.

@il-steffen any thoughts ?

**Comment by il-steffen** [comment]
Yes, seems like someone else's problem. The error handling is terrible but apparently also not our fault.
